spring:
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db.akko.space:3306/uc
    username: uc
    password: Mrmn5CdfpPiWRKx2
    # Session Config
  session:
    # 一天 60*60*24 = 86400
    timeout: 86400
server:
  address: 0.0.0.0